version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - DATABASE_URL=${DATABASE_URL}
        - SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}
    networks:
      - tw-network
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}
    # Добавить вольюмы для node_modules
    volumes:
      - backend-node_modules:/app/node_modules  # Путь должен совпадать с WORKDIR в Dockerfile

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks:
      - tw-network
    image: frontend
    # Добавить вольюмы для node_modules
    volumes:
      - frontend-node_modules:/app/node_modules  # Путь должен совпадать с WORKDIR в Dockerfile

  nginx:
    build:
      context: ./nginx
      args:
        FRONTEND_IMAGE: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - frontend
    networks:
      - tw-network

networks:
  tw-network:
    driver: bridge

# Добавить секцию volumes в конец файла
volumes:
  backend-node_modules:
  frontend-node_modules: