version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: myapp-backend
    networks:
      - app-network
    expose:
      - 3000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: myapp-frontend
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80"
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge