version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    image: frontend # Явное имя образа

  nginx:
    build:
      context: ./nginx
      args:
        FRONTEND_IMAGE: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always