version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        - DATABASE_URL=${DATABASE_URL}
        - SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}
    networks:
      - tw-network
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - tw-network
    image: frontend

  nginx:
    build:
      context: ./nginx
      args:
        FRONTEND_IMAGE: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - frontend
    networks:
      - tw-network

networks:
  tw-network:
    driver: bridge