version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}
        - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY}
        - PM2_SECRET_KEY=${PM2_SECRET_KEY}
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}
      - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY}
      - PM2_SECRET_KEY=${PM2_SECRET_KEY}
    networks:
      - tw-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - tw-network
    image: frontend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        FRONTEND_IMAGE: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - frontend
    networks:
      - tw-network

networks:
  tw-network:
    driver: bridge