version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - 3000
    networks:
      - tw-network
    environment:
      - NODE_ENV=production
      - PORT=3000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks:
      - tw-network
    image: frontend

  nginx:
    build:
      context: ./nginx
      args:
        FRONTEND_IMAGE: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - frontend
    networks:
      - tw-network

networks:
  tw-network:
    driver: bridge