version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - 3000
    networks:
      - tw-network
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks:
      - tw-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - tw-network

networks:
  tw-network:
    driver: bridge