FROM node:18-alpine AS builder

WORKDIR /app
COPY client/package*.json .
RUN npm install
COPY client/ .
RUN npm run build

FROM alpine:latest
RUN mkdir -p /usr/share/nginx/html
COPY --from=builder /app/dist /usr/share/nginx/html