version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend